# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://laravel.api/api/v1/signin
Content-Type: application/json

{
  "email": "wisoky.dejon@example.net",
  "password": "password"
}

> {%
client.global.set("user_id", response.body.id);
client.global.set("bearer_token", response.headers.valueOf('access_token'));
%}

###

GET http://laravel.api/api/v1/subscriptions/create
Content-Type: application/json
Authorization: Bearer {{bearer_token}}

###

GET http://laravel.api/api/v1/payments/create
Content-Type: application/json
Authorization: Bearer {{bearer_token}}

###

POST http://laravel.api/api/v1/subscriptions
Content-Type: application/json
Authorization: Bearer {{bearer_token}}

###